APPLICATION = hello-world

# If no BOARD is found in the environment, use this default:
BOARD ?= nrf52840

# This has to be the absolute path to the NDN Lite base directory:
LIBBASE ?= $(CURDIR)/../..

include $(LIBBASE)/Makefile.top
